version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd YYduo-Be
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./YYduo-Be/build/libs/*.jar)
artifacts:
  files:
    - YYduo-Be/build/libs/*.jar
    - YYduo-Be/scripts/**
    - YYduo-Be/appspec.yml
  discard-paths: yes
