version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd kkuldong
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./kkuldong/build/libs/*.jar)
artifacts:
  files:
    - kkuldong/build/libs/*.jar
    - kkuldong/scripts/**
    - kkuldong/appspec.yml
  discard-paths: yes
