server:
  port: 8080
  address:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkuldong
    username: ${MYSQL_LOCAL_USERNAME}
    password: ${MYSQL_LOCAL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create # (1) ??? ?? ??  update -> create 변ㄱ
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database: mysql

